In [7]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [9]:
array = np.linspace(-3,3,num=100)


In [10]:
array * 10


array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18

In [11]:
np.random.randint(50,size=100,high=101)

array([ 77,  63,  60,  91,  81,  54,  84,  69,  73,  96,  80,  65,  96,
        70,  78,  82,  87,  77,  59,  92,  98,  75,  82,  94,  84,  73,
        59,  66,  61,  93,  80,  51,  76,  77,  63,  87,  78,  60,  97,
        86,  66,  63,  60,  54,  97,  90,  85,  97,  76,  86,  67,  83,
        62,  66,  94,  88,  86,  90,  73,  80,  71,  96,  54,  54,  79,
        80,  78,  76,  60,  59,  51, 100,  84,  98,  86,  70,  56,  88,
        69,  55,  70,  84,  57,  63,  61,  81,  82,  50,  77,  56,  56,
        53,  79,  58,  77,  91,  64,  58,  99,  75])

In [12]:

content = np.random.randint(50,size=(50,5),high=101)

In [13]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=[f"第{i}號"for i in range(1,51)],
             columns=['國文','英文','數學','地理','歷史'])
df1

國文   英文  數學   地理   歷史
第1號   59   78  86   55   83
第2號   68   53  78   59   74
第3號   64   98  86   72   77
第4號   61   73  86   70   82
第5號   84   65  85   58   54
第6號   98   60  51   55   84
第7號   50   54  62   64   88
第8號   88  100  64   98   61
第9號   67   70  85   91   61
第10號  70   99  66   90   75
第11號  51   66  63   67   99
第12號  99   85  80   78   66
第13號  95   80  89   52   52
第14號  90  100  97   76   54
第15號  65   94  90   66   75
第16號  72   51  73  100   54
第17號  57   78  79   74   84
第18號  63   57  84   99   56
第19號  79   58  96   68   83
第20號  80   74  62   59   81
第21號  50  100  96   80   92
第22號  72   64  86   84   68
第23號  53   79  98   57   71
第24號  80   72  82   74  100
第25號  82   83  78   98   50
第26號  97   83  77   62   77
第27號  63   61  89   56   77
第28號  98   54  61   55   52
第29號  93   83  78   99   66
第30號  79   92  93   57   94
第31號  68   76  56   53   80
第32號  77   73  67   88   90
第33號  92   93  93   57   67
第34號  58   90  95   69   52
第35號  99   95  89   68   65
第36號  73   79  70   61   75
第37號  83   66  82   92   59
第38號  93   57  82   98   78
第39號  68   58  59   51   84
第40號  75   69  52   65   75
第41號  83   59  64   61   68
第42號  89   96  82   58   55
第43號  75   77  58   98   53
第44號  75   91  87  100   96
第45號  79   63  90   93   61
第46號  72   55  72   79   83
第47號  83   80  90   60   72
第48號  95   92  84   95   66
第49號  76   61  70   73   94
第50號  66   79  52   58   73

In [ ]:
np.linspace(-3,3,2) 

array([-3.,  3.])

In [ ]:
np.linspace(-3,3,100)

array([-3.        , -2.93939394, -2.87878788, -2.81818182, -2.75757576,
       -2.6969697 , -2.63636364, -2.57575758, -2.51515152, -2.45454545,
       -2.39393939, -2.33333333, -2.27272727, -2.21212121, -2.15151515,
       -2.09090909, -2.03030303, -1.96969697, -1.90909091, -1.84848485,
       -1.78787879, -1.72727273, -1.66666667, -1.60606061, -1.54545455,
       -1.48484848, -1.42424242, -1.36363636, -1.3030303 , -1.24242424,
       -1.18181818, -1.12121212, -1.06060606, -1.        , -0.93939394,
       -0.87878788, -0.81818182, -0.75757576, -0.6969697 , -0.63636364,
       -0.57575758, -0.51515152, -0.45454545, -0.39393939, -0.33333333,
       -0.27272727, -0.21212121, -0.15151515, -0.09090909, -0.03030303,
        0.03030303,  0.09090909,  0.15151515,  0.21212121,  0.27272727,
        0.33333333,  0.39393939,  0.45454545,  0.51515152,  0.57575758,
        0.63636364,  0.6969697 ,  0.75757576,  0.81818182,  0.87878788,
        0.93939394,  1.        ,  1.06060606,  1.12121212,  1.18

In [ ]:
array = np.linspace(-3,3,num=100)


In [ ]:
np.random.randint(50,101,2)

array([73, 73])

In [ ]:
np.random.randint(50,size=(50,5),high=101)
#但缺點是沒有列數，所以分不出來，但pandas可以

array([[ 89,  51,  86,  90,  86],
       [ 73,  53,  85,  71,  71],
       [ 94,  64,  95,  69,  61],
       [ 56,  85,  61,  98,  69],
       [ 84,  66,  83,  58,  54],
       [ 53,  68,  63,  68,  95],
       [ 52,  88,  56,  53,  62],
       [ 98,  62,  94,  52,  98],
       [ 91,  86,  84,  92,  77],
       [ 85,  54,  84,  64,  89],
       [ 51,  58,  64,  74,  79],
       [ 81,  51,  57,  51,  55],
       [ 92,  63,  88,  93, 100],
       [ 60,  70,  56,  56,  74],
       [ 56,  51,  92,  94,  62],
       [ 57,  86,  82,  64,  53],
       [ 53,  84,  77,  92,  89],
       [ 89,  95,  99,  59,  94],
       [ 91,  64,  84,  73,  67],
       [ 61,  71,  75,  72,  69],
       [ 92,  71,  99,  76,  98],
       [ 98,  58,  87,  70,  94],
       [ 52,  64,  59,  90,  82],
       [ 53,  90,  80,  80,  91],
       [ 87,  75,  79,  95,  82],
       [ 90,  59,  67,  88,  71],
       [ 65,  92,  96,  72,  64],
       [ 74,  82,  84,  80,  82],
       [ 62, 100,  80,  94,  75],
       [ 93,  

In [ ]:
content=np.random.randint(50,size=(50,5),high=101)

In [ ]:
import pandas as pd
df1=pd.DataFrame(data=content,
             index=[f"第{i}號"for i in range(1,51)],
             columns=['國文','英文','數學','自然','社會'])
df1

國文   英文   數學   自然   社會
第1號    65   58   59   99   60
第2號    70   82   76  100   75
第3號    85   71   86   53   72
第4號    84   97   99   72   82
第5號    68   86   82   55   54
第6號    62   64  100   52   50
第7號    58   51   89   98   72
第8號    55   62   57   56   55
第9號    86   97   91   93   68
第10號   81   59   59  100   92
第11號   81   82   92   65   68
第12號   81   72   75   72   70
第13號   91   84   93   55   71
第14號   68   95   79   80   51
第15號   78   52   91   84   76
第16號   75   73   71   68   65
第17號   97   64   89   71   85
第18號   76   99   83   86   82
第19號   85  100   78  100   90
第20號   63   76   99   69   89
第21號   78   98   77   99   84
第22號   69   90   64   90   64
第23號   81   77   97   83   58
第24號   92   57   56   83   80
第25號   99   95   80   57   90
第26號   96   67   66   67   50
第27號   73   69   97   74   82
第28號   85   74   66   55   73
第29號   82   90   77   63   89
第30號   80   51   50   85   94
第31號   79   67   84   74   81
第32號   63   59   54   94   79
第33號  100   89   70   90  100
第34號   69   89   77   67   85
第35號   63   74   76   77   69
第36號   69   95   65   98   64
第37號   93   69   78   54   67
第38號   60   52   53   69   97
第39號   53   84   89   75   73
第40號   89   92   61   83   95
第41號   87   61   75   94   63
第42號   71   85   89   60   76
第43號   79   81   63   71   59
第44號   88   62   85   77   70
第45號   83   94   80   92   64
第46號   64   92   55   92   71
第47號   64   52   85   66   77
第48號   91   79  100   53   67
第49號   82   78   83  100   95
第50號   53   63   79   61   63

In [14]:
df1.loc["第1號"]

國文    59
英文    78
數學    86
地理    55
歷史    83
Name: 第1號, dtype: int64

In [ ]:
df1['國文']

第1號      65
第2號      70
第3號      85
第4號      84
第5號      68
第6號      62
第7號      58
第8號      55
第9號      86
第10號     81
第11號     81
第12號     81
第13號     91
第14號     68
第15號     78
第16號     75
第17號     97
第18號     76
第19號     85
第20號     63
第21號     78
第22號     69
第23號     81
第24號     92
第25號     99
第26號     96
第27號     73
第28號     85
第29號     82
第30號     80
第31號     79
第32號     63
第33號    100
第34號     69
第35號     63
第36號     69
第37號     93
第38號     60
第39號     53
第40號     89
第41號     87
第42號     71
第43號     79
第44號     88
第45號     83
第46號     64
第47號     64
第48號     91
第49號     82
第50號     53
Name: 國文, dtype: int64

In [ ]:
df1['國文']+df1['英文']

第1號     123
第2號     152
第3號     156
第4號     181
第5號     154
第6號     126
第7號     109
第8號     117
第9號     183
第10號    140
第11號    163
第12號    153
第13號    175
第14號    163
第15號    130
第16號    148
第17號    161
第18號    175
第19號    185
第20號    139
第21號    176
第22號    159
第23號    158
第24號    149
第25號    194
第26號    163
第27號    142
第28號    159
第29號    172
第30號    131
第31號    146
第32號    122
第33號    189
第34號    158
第35號    137
第36號    164
第37號    162
第38號    112
第39號    137
第40號    181
第41號    148
第42號    156
第43號    160
第44號    150
第45號    177
第46號    156
第47號    116
第48號    170
第49號    160
第50號    116
dtype: int64

In [ ]:
df1.loc['第1號',:]

國文    65
英文    58
數學    59
自然    99
社會    60
Name: 第1號, dtype: int64

In [ ]:
df1.loc['第1號']

國文    65
英文    58
數學    59
自然    99
社會    60
Name: 第1號, dtype: int64

In [ ]:
df1.iloc[:5]

國文  英文  數學   自然  社會
第1號  65  58  59   99  60
第2號  70  82  76  100  75
第3號  85  71  86   53  72
第4號  84  97  99   72  82
第5號  68  86  82   55  54

In [ ]:
df1.iloc[:5,:3]

國文  英文  數學
第1號  65  58  59
第2號  70  82  76
第3號  85  71  86
第4號  84  97  99
第5號  68  86  82

In [ ]:
df1.iloc[-3:,:3]

國文  英文   數學
第48號  91  79  100
第49號  82  78   83
第50號  53  63   79

In [ ]:
df1.loc['第10號':'第15號']

國文  英文  數學   自然  社會
第10號  81  59  59  100  92
第11號  81  82  92   65  68
第12號  81  72  75   72  70
第13號  91  84  93   55  71
第14號  68  95  79   80  51
第15號  78  52  91   84  76

In [ ]:
df1.loc[["第1號","第5號","第10號"]]

國文  英文  數學   自然  社會
第1號   65  58  59   99  60
第5號   68  86  82   55  54
第10號  81  59  59  100  92

In [18]:
student_sum=df1.sum(axis=1)
student_mean=df1.mean(axis=1)
df1['總分'] = student_sum
df1['平均'] = student_mean

In [19]:
df1

國文   英文  數學   地理   歷史   總分    平均
第1號   59   78  86   55   83  361  72.2
第2號   68   53  78   59   74  332  66.4
第3號   64   98  86   72   77  397  79.4
第4號   61   73  86   70   82  372  74.4
第5號   84   65  85   58   54  346  69.2
第6號   98   60  51   55   84  348  69.6
第7號   50   54  62   64   88  318  63.6
第8號   88  100  64   98   61  411  82.2
第9號   67   70  85   91   61  374  74.8
第10號  70   99  66   90   75  400  80.0
第11號  51   66  63   67   99  346  69.2
第12號  99   85  80   78   66  408  81.6
第13號  95   80  89   52   52  368  73.6
第14號  90  100  97   76   54  417  83.4
第15號  65   94  90   66   75  390  78.0
第16號  72   51  73  100   54  350  70.0
第17號  57   78  79   74   84  372  74.4
第18號  63   57  84   99   56  359  71.8
第19號  79   58  96   68   83  384  76.8
第20號  80   74  62   59   81  356  71.2
第21號  50  100  96   80   92  418  83.6
第22號  72   64  86   84   68  374  74.8
第23號  53   79  98   57   71  358  71.6
第24號  80   72  82   74  100  408  81.6
第25號  82   83  78   98   50  391  78.2
第26號  97   83  77   62   77  396  79.2
第27號  63   61  89   56   77  346  69.2
第28號  98   54  61   55   52  320  64.0
第29號  93   83  78   99   66  419  83.8
第30號  79   92  93   57   94  415  83.0
第31號  68   76  56   53   80  333  66.6
第32號  77   73  67   88   90  395  79.0
第33號  92   93  93   57   67  402  80.4
第34號  58   90  95   69   52  364  72.8
第35號  99   95  89   68   65  416  83.2
第36號  73   79  70   61   75  358  71.6
第37號  83   66  82   92   59  382  76.4
第38號  93   57  82   98   78  408  81.6
第39號  68   58  59   51   84  320  64.0
第40號  75   69  52   65   75  336  67.2
第41號  83   59  64   61   68  335  67.0
第42號  89   96  82   58   55  380  76.0
第43號  75   77  58   98   53  361  72.2
第44號  75   91  87  100   96  449  89.8
第45號  79   63  90   93   61  386  77.2
第46號  72   55  72   79   83  361  72.2
第47號  83   80  90   60   72  385  77.0
第48號  95   92  84   95   66  432  86.4
第49號  76   61  70   73   94  374  74.8
第50號  66   79  52   58   73  328  65.6

In [20]:
df2=df1.sort_values(by='總分',ascending=False)

In [21]:
df2.iloc[:5]

國文   英文  數學   地理  歷史   總分    平均
第44號  75   91  87  100  96  449  89.8
第48號  95   92  84   95  66  432  86.4
第29號  93   83  78   99  66  419  83.8
第21號  50  100  96   80  92  418  83.6
第14號  90  100  97   76  54  417  83.4

In [22]:
df2['排名']=df1['總分'].rank(method='first',ascending=False)

In [23]:
df2

國文   英文  數學   地理   歷史   總分    平均    排名
第44號  75   91  87  100   96  449  89.8   1.0
第48號  95   92  84   95   66  432  86.4   2.0
第29號  93   83  78   99   66  419  83.8   3.0
第21號  50  100  96   80   92  418  83.6   4.0
第14號  90  100  97   76   54  417  83.4   5.0
第35號  99   95  89   68   65  416  83.2   6.0
第30號  79   92  93   57   94  415  83.0   7.0
第8號   88  100  64   98   61  411  82.2   8.0
第12號  99   85  80   78   66  408  81.6   9.0
第38號  93   57  82   98   78  408  81.6  11.0
第24號  80   72  82   74  100  408  81.6  10.0
第33號  92   93  93   57   67  402  80.4  12.0
第10號  70   99  66   90   75  400  80.0  13.0
第3號   64   98  86   72   77  397  79.4  14.0
第26號  97   83  77   62   77  396  79.2  15.0
第32號  77   73  67   88   90  395  79.0  16.0
第25號  82   83  78   98   50  391  78.2  17.0
第15號  65   94  90   66   75  390  78.0  18.0
第45號  79   63  90   93   61  386  77.2  19.0
第47號  83   80  90   60   72  385  77.0  20.0
第19號  79   58  96   68   83  384  76.8  21.0
第37號  83   66  82   92   59  382  76.4  22.0
第42號  89   96  82   58   55  380  76.0  23.0
第49號  76   61  70   73   94  374  74.8  26.0
第22號  72   64  86   84   68  374  74.8  25.0
第9號   67   70  85   91   61  374  74.8  24.0
第4號   61   73  86   70   82  372  74.4  27.0
第17號  57   78  79   74   84  372  74.4  28.0
第13號  95   80  89   52   52  368  73.6  29.0
第34號  58   90  95   69   52  364  72.8  30.0
第46號  72   55  72   79   83  361  72.2  33.0
第43號  75   77  58   98   53  361  72.2  32.0
第1號   59   78  86   55   83  361  72.2  31.0
第18號  63   57  84   99   56  359  71.8  34.0
第23號  53   79  98   57   71  358  71.6  35.0
第36號  73   79  70   61   75  358  71.6  36.0
第20號  80   74  62   59   81  356  71.2  37.0
第16號  72   51  73  100   54  350  70.0  38.0
第6號   98   60  51   55   84  348  69.6  39.0
第27號  63   61  89   56   77  346  69.2  42.0
第5號   84   65  85   58   54  346  69.2  40.0
第11號  51   66  63   67   99  346  69.2  41.0
第40號  75   69  52   65   75  336  67.2  43.0
第41號  83   59  64   61   68  335  67.0  44.0
第31號  68   76  56   53   80  333  66.6  45.0
第2號   68   53  78   59   74  332  66.4  46.0
第50號  66   79  52   58   73  328  65.6  47.0
第28號  98   54  61   55   52  320  64.0  48.0
第39號  68   58  59   51   84  320  64.0  49.0
第7號   50   54  62   64   88  318  63.6  50.0